version: "3.8"
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  bot:
    build:
      context: ./bot
      target: builder
    image: bot
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bot.rule=Host(`localhost`) && PathPrefix(`/bot`)"
    environment:
      - ENV=dev
    volumes:
      - ./bot:/go/src/app
    depends_on:
      - reverse-proxy
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
  bot-client:
    build: 
      context: ./bot-client
    image: bot-client
    expose:
      - "3000"
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bot-client.rule=Host(`localhost`) && PathPrefix(`/account`)"
    volumes:
      - ./bot-client:/app
      - /app/node_modules
    depends_on:
      - reverse-proxy